on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Convert test file to png image
        uses: Burnett01/actions-drawio@1.0
        with:
          src: database-er-diagram.drawio
          dest: database-er-diagram.png
      - name: Upload image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: png
          path: database-er-diagram.png